### ISSUE TITLE
collision String method name "b" with Ruby 2.1

### ISSUE THREAD

**Issue by JokerCatz** [rubyworks/radix#10]
sorry for my poor english...

Ruby 2.1.0 String.b #=> http://www.ruby-doc.org/core-2.1.0/String.html#method-i-b

& I tried require(gemfile) radix in rails & use will be fail
`
~/.rvm/gems/ruby-2.1.0/gems/radix-2.2.0/lib/radix/operator.rb:51:in 'b': wrong number of arguments (0 for 1) (ArgumentError)
    from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/erb.rb:600:in 'compile'
    from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/erb.rb:800:in 'initialize'
`

**Comment by trans** [comment]
Been busy with other work this last year (android development) and just learned about this (unfortunately I don't always get issue emails, not sure why). So I just put in an issue at bugs.ruby-lang.org, asking that the method name be changes. Seem to me an awful name for ascii 8-bit conversion, anyway. The obvious choice being `#ascii`. Of course, I don't have high hopes for my request. They never give me much credence, so barring thata miracle, what is the next best fix? Any ideas?
